// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoZW5kA0S6hfSIC4a1ym3qJsxXByrSOvE',
    appId: '1:493522190860:web:601168f8e14da04a166429',
    messagingSenderId: '493522190860',
    projectId: 'plannier-5b64c',
    authDomain: 'plannier-5b64c.firebaseapp.com',
    storageBucket: 'plannier-5b64c.appspot.com',
    measurementId: 'G-54VJXLNQLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3F-f84ERDOK16LuYHrQedboSJRm0AVhs',
    appId: '1:493522190860:android:3b2e28f0177e69a8166429',
    messagingSenderId: '493522190860',
    projectId: 'plannier-5b64c',
    storageBucket: 'plannier-5b64c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJrQWYjJqqIaQ9CmaoFjfkFJBfiOezcNk',
    appId: '1:493522190860:ios:04c6c35d28816be5166429',
    messagingSenderId: '493522190860',
    projectId: 'plannier-5b64c',
    storageBucket: 'plannier-5b64c.appspot.com',
    iosClientId: '493522190860-cg6j0mpg08tnvr41e58ij7ln8j69qqn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.plannier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJrQWYjJqqIaQ9CmaoFjfkFJBfiOezcNk',
    appId: '1:493522190860:ios:04c6c35d28816be5166429',
    messagingSenderId: '493522190860',
    projectId: 'plannier-5b64c',
    storageBucket: 'plannier-5b64c.appspot.com',
    iosClientId: '493522190860-cg6j0mpg08tnvr41e58ij7ln8j69qqn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.plannier',
  );
}
